RevistaJuridica/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RevistaJuridica.Controllers
{
    public class AboutController : Controller
    {
        public ActionResult Index()
        {
            return View ();
        }
    }
}

RevistaJuridica/Controllers/ArticleController.cs
using System;
using System.IO;
using System.Web;
using System.Web.Mvc;
using RevistaJuridica.ArticleRepositories;
using RevistaJuridica.Models;

namespace RevistaJuridica.Controllers
{
    public class ArticleController : Controller
    {
        private readonly ArticleRepository repo = new ArticleRepository();

        public ActionResult Index()
        {

            return View(repo.GetAllArticles());
        }

        public ActionResult New()
        {
            return View();
        }

        [HttpPost]
        public ActionResult New(Article e)
        {
            repo.InsertArticle(e);

            return RedirectToAction("Index");
        }

        public ActionResult Details(long id)
        {
            var e = repo.GetArticle(id);

            return View(e);
        }

        [HttpPost]
        public ActionResult Edit(Article e)
        {
            repo.UpdateArticle(e);

            return RedirectToAction("Index");
        }

        public ActionResult Delete(Models.Article e)
        {
            repo.DeleteArticle(e);

            return RedirectToAction("Index");
        }
    }
}

RevistaJuridica/Controllers/EditionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RevistaJuridica.Repositories;

namespace RevistaJuridica.Controllers
{
    public class EditionController : Controller
    {
        private readonly EditionRepository repo = new EditionRepository();

        public ActionResult Index()
        {
            return View(repo.GetAllEditionsWithNumbersAndArticles());
        }
    }
}

RevistaJuridica/Controllers/EventController.cs
using System;
using System.Web.Mvc;
using RevistaJuridica.Models;
using RevistaJuridica.EventRepositories;
using System.Web;
using System.IO;
using RevistaJuridica.Repositories;

namespace RevistaJuridica.Controllers
{
    public class EventController : Controller
    {
        private readonly EventRepository repo = new EventRepository();

        public ActionResult Index()
        {
           
            return View(repo.GetAllEvents());
        }

        public ActionResult Details(long id)
        {
            var e = repo.GetEventWithImage(id);

            return View("Details", e);
        }

        public ActionResult New()
        {
            return View();
        }

        [HttpPost]
        public ActionResult New(Event e)
        {
            e.EventDate = DateTime.Now;

            _ = repo.InsertEvent(e);

            return RedirectToAction("Index");
        }

        public ActionResult Edit(long id)
        {
            var e = repo.GetEvent(id);

            return View(e);
        }

        [HttpPost]
        public ActionResult Edit(Event e, HttpPostedFileBase file)
        {

            if (file != null && file.ContentLength > 0)
                try
                {
                    string path = Path.Combine(Server.MapPath("~/Documents/Events"), Path.GetFileName(file.FileName));

                    //Document Validation
                    DocumentRepository docRepo = new DocumentRepository();

                    Document eventImage = repo.GetEventImage(e.Id);

                    if(eventImage != null)
                    {
                        // Remove Old Image
                        System.IO.File.Delete(Path.Combine(Server.MapPath("~/Documents/Events"), eventImage.Name));

                        Document newEventImage = new Document();
                        eventImage.Name = file.FileName;
                        eventImage.Type = file.ContentType;
                        eventImage.Size = file.ContentLength;
                        eventImage.Path = path;
                  
                        //Update Event Image information
                        docRepo.UpdateDocument(eventImage);
                    }
                    else
                    {
                        Document newEventImage = new Document();

                        newEventImage.Name = file.FileName;
                        newEventImage.Type = file.ContentType;
                        newEventImage.Size = file.ContentLength;
                        newEventImage.Path = path;
                        newEventImage.SourceTypeId = docRepo.GetDocumentSourceTypeId("DocumentSource", "EventImage");

                        //Save new Image information
                        docRepo.InsertDocument(newEventImage);
                    }
                    // Save Image on Server
                    file.SaveAs(path);

                    ViewBag.Message = "File uploaded successfully";
                }
                catch (Exception ex)
                {
                    ViewBag.Message = "ERROR:" + ex.Message.ToString();
                }
            else
            {
                ViewBag.Message = "You have not specified a file.";
            }

            repo.UpdateEvent(e);

            return RedirectToAction("Edit");
        }

        public ActionResult Delete(Event e)
        {
            repo.DeleteEvent(e);

            return RedirectToAction("Index");
        }
    }
}

RevistaJuridica/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Revista Jurídica</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed:300,300i,400,400i,700,700i|Roboto:100,300,400,400i,700,700i" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="~/Resources/style.css" />
    <link rel="stylesheet" type="text/css" href="~/Resources/DataTables/datatables.min.css" />
</head>
<body>
    <header class="site-header" style="background-color:rgba(0, 0, 0, .68);">
        <div class="container">
            <h1 class="school-logo-text float-left"><a href="@Url.Action("Index", "Home")"><strong>Revista</strong> Jurídica UIPR</a></h1> 
            <div class="site-header__menu group">
                <nav class="main-navigation">
                    <ul>
                        <li>@Html.ActionLink("Conócenos", "Index", "About")</li>
                        <li>@Html.ActionLink("Volúmenes", "Index", "Edition")</li>
                        <li>@Html.ActionLink("Convocatorias", "Index", "Announcement")</li>
                        <li>@Html.ActionLink("Eventos", "Index", "Event")</li>
                        <li><a href="#">Contáctanos</a></li>
                        <li><a href="#">Materiales</a></li>
                        <li><a href="#">Galería</a></li>
                        <li><a href="#">Someter Artículo</a></li>
                    </ul>
                </nav>

            </div>
        </div>
    </header>

    @RenderBody()

    <footer class="site-footer">

        <div class="site-footer__inner container container--narrow">

            <div class="group">

                <div class="site-footer__col-one">
                    <h1 class="school-logo-text school-logo-text--alt-color"><a href="#"><strong>Revista</strong> Jurídica</a></h1>
                    <p>
                        <a class="site-footer__link" href="#">
                            <span>
                                <i class="fas fa-phone"></i>
                            </span>
                            (787)751-1912  #2078</a>
                    </p>
                </div>

                <div class="site-footer__col-two-three-group">
                    <div class="site-footer__col-two">
                        <h3 class="headline headline--small"></h3>
                        <nav class="nav-list">
                            <ul>
                                <li>@Html.ActionLink("Conócenos", "Index", "About")</li>
                                <li>@Html.ActionLink("Volúmenes", "Index", "Article")</li>
                                <li>@Html.ActionLink("Eventos", "Index", "Event")</li>
                                <li><a href="#">Contáctanos</a></li>
                            </ul>
                        </nav>
                    </div>

                    <div class="site-footer__col-three">
                        <h3 class="headline headline--small"></h3>
                        <nav class="nav-list">
                            <ul>
                            </ul>
                        </nav>
                    </div>
                </div>

                <div class="site-footer__col-four">
                    <h3 class="headline headline--small">Síguenos</h3>
                    <nav>
                        <ul class="min-list social-icons-list group">
                            
                            <li><a href="https://www.facebook.com/revistajuridicainter/" class="social-color-facebook"><span><i class="fa facebook-square"></i></span></a></li>
                            <li><a href="#" class="social-color-instagram"><span class="fa fa-instagram"></span></a></li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </footer>
    <script src="https://kit.fontawesome.com/b29dee2e36.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="~/Resources/js/scripts-bundled.js"></script>
    <script type="text/javascript" src="~/Resources/DataTables/datatables.min.js"></script>
</body>
</html>